### ISSUE TITLE
Will this be updated on steam also?

### ISSUE THREAD

**Issue by slider6996** [VeraciousNetwork/PZ-VNGarage#6]
Just seeing if this would be updated to the steam also as i saw the pull was merged but the version on steam has not been updated yet, not sure how that works as im still using the private custom patch i made to have all the tires and was about to disable but then noticed the steam one was still showing last update from Jan, no rush just curious.

**Comment by cdp1337** [comment]
Yes, but I would like to get some more features added this week as well.  I'll update this ticket once I get everything released.

**Comment by slider6996** [comment]
Oh your good I never dabbled in a github PZ mod and I had assumed it auto updated the steam version once it was merged so your good, no rush on it. I'll keep eye out for more vehicles also and can update on the fork when one updates as i believe he is updating several of his vehicles on KI5 and added new tires or any from other authors but ya look forward to the features :)

**Comment by cdp1337** [comment]
It has the ability to do so, but I don't have it setup to do that.  I'd need to export `deploy_dist.sh` to a CI deployment script (which would be relatively trivial), but I don't have any automated unit tests for the game so I prefer to run `deploy_local.sh` to test locally before I publish work to the community.

And of course KI5 is adding more tires, :roll_eyes: .  This is why I personally don't run their mods on our server; having different tires for each different vehicle is just silly.  But alas having support for their crazy items is still advantageous.  If you have more tires to add, feel free to submit a merge request and I'll get it put in.

(also a teaser of what I'm working on this week ;) )
![image](https://github.com/user-attachments/assets/8addeec5-566f-4fc0-ab7c-5d759d439d0f)

**Comment by slider6996** [comment]
Ya like i never dabbled in making a patch for a mod and your mod is one of the mods i always have since i always do a mechanic style build in someways and storing tires in tiny crates never felt correct and when i learned it didn't work with KI5 tires or least the newer ones i was bummed cause he has so many custom tires but u wrote the mod in a way that made it simple to make a patch for them was just time consuming a little but once i found a pace it wasn't to bad and mod is simply a must have i feel like.

And love the update as i was thinking that myself it be cool if it showed different sizes but i was satisfied how it was really but glad its getting some updates and good ones.

Ya I browsed a few mods from different authors on cars and several i checked used the vanilla style already added. I havent checked the new animation beta of fill busters but I assume they probably use vanilla also but ill check, or if u know of any collections that use custom ones i can work on those too. Far as i can tell KI5 only one using custom tires.

**Comment by cdp1337** [comment]
Published to steam.
